# Consultas de Prometheus para monitorear las funciones de red UPF
cpu_usage: 'sum(rate(container_cpu_usage_seconds_total{pod=~"free5gc-upf.*"}[5m])) by (pod)'
memory_usage: 'sum(container_memory_usage_bytes{pod=~"free5gc-upf.*"}) by (pod)'
network_in: 'sum(rate(container_network_receive_bytes_total{pod=~"free5gc-upf.*"}[5m])) by (pod)'
network_out: 'sum(rate(container_network_transmit_bytes_total{pod=~"free5gc-upf.*"}[5m])) by (pod)'
# disk_usage: 'sum(container_fs_usage_bytes{pod=~"free5gc-upf.*"}) by (pod)'
